# This is a basic workflow to help you get started with Actions

name: deploy_to_cocoapods

on:
    push:
        tags:
        - "*.*.*"

jobs:
    build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Publish to CocoaPod register
        env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
        pod trunk push RxSchoolMeal.podspec
