# This is a basic workflow to help you get started with Actions

name: main

on:
  push:
    tags:
        - '*'

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install Cocoapods
      run: gem install cocoapods
    - name: build and test
      run: |
        swift build
        swift test --enable-code-coverage
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
    - name: Deploy to SPM
      run: swift package generate-xcodeproj
    - name: Upload Codecov report
      run: |
        bundle exec slather
        bash <(curl -s https://codecov.io/bash) -f xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
