# This is a basic workflow to help you get started with Actions

name: pr

on: pull_request

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: build
      run: swift build
    - name: test
      run: |
        swift package generate-xcodeproj
        xcodebuild test -scheme RxSchoolMeal-Package -destination \platform="macOS" -enableCodeCoverage YES
    - name: Upload Codecov report
      run: |
        bash <(curl -s https://codecov.io/bash)
