# This is a basic workflow to help you get started with Actions

name: pr

on: pull_request

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: build
      run: swift build
    - name: test
      run: swift test
    - name: Upload Codecov report
      run: |
        llvm-cov export -format="lcov" .build/debug/SwiftLoggerPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
        bash <(curl -s https://codecov.io/bash) -J 'RxSchoolMeal'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
