# This is a basic workflow to help you get started with Actions

name: pr

on: pull_request

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - uses: szenius/set-timezone@v1.0
      with:
        timezoneMacos: "Asia/Seoul"
    - name: build
      run: swift build
    - name: SwiftPM tests
      run: swift test --enable-code-coverage
    - name: Convert coverage to lcov
      run: xcrun llvm-cov export -format="lcov" .build/debug/RxSchoolMealPackageTests.xctest/Contents/MacOS/RxSchoolMealPackageTests -instr-profile .build/debug/codecov/default.profdata > coverage.lcov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
