# This is a basic workflow to help you get started with Actions

name: pr

on: pull_request

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: build
      run: swift build
    - name: test
      run: swift test --enable-code-coverage
    - name: Upload Codecov report
      run: |
        xcodebuild -scheme RxSchoolMeal -workspace .swiftpm/xcode/package.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=12' build test
        bash <(curl -s https://codecov.io/bash) -J 'RxSchoolMeal'
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
