# This is a basic workflow to help you get started with Actions

name: pr

on: pull_request

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: build
      run: swift build
    - name: path check
      run: |
        cd ./swiftpm/xcode
        ls
    - name: test
      run: |
        swift test --enable-code-coverage
    - name: Upload Codecov report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: .build/x86_64-apple-macosx/debug/codecov/RxSchoolMeal.json
        fail_ci_if_error: true
