# This is a basic workflow to help you get started with Actions

name: pr

on: pull_request

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: build
      run: swift build
    - name: test
      run: |
        swift test --enable-code-coverage
    - name: Upload Codecov report
      run: |
        bundle config path vendor/bundle
        bundle install --without=documentation --jobs 4 --retry 3
        bundle exec slather
        bash <(curl -s https://codecov.io/bash) -f xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
